### ISSUE TITLE
Select Segment from Box crashes in Krita 5.3.0 Prealpha

### ISSUE THREAD

**Issue by feureau** [Acly/krita-ai-tools#1]
Hi! thanks for this awesome tool!
Just want to report this issue I've been getting.

When using Box Segmentation Selection tool, after selecting an object, switching to other tool would crash Krita.
I'm not sure how reproducible this is on other machines, but it's consistent on my install in that the tool always crashes Krita entirely when switching away to other tools.

I was wondering how to fix this/if other people been having the same issue?

Thanks again.

**Comment by Acly** [comment]
I can reproduce this with 5.3.0prealpha, and also with 5.2.0rc1 actually. But 5.2.0 beta1 and beta2 work fine.

Did you build the plugin yourself? The binaries from the release page can only be reliably used with the Krita version they were built for - in this case 5.2.0 beta1.

I'll look into this for 5.2.0rc1, no promises on nightly builds, but afaik they're quite similar at the moment.

**Comment by feureau** [comment]
Thanks for looking into this. I got the plugin from the GitHub release.
I'll just switch to 5.2.0b1 for now. Thanks again!

**Comment by Acly** [comment]
I just built the plugin for 5.2.0 RC1 and it fixed the crash for me. Probably also works for the nightly.

https://github.com/Acly/krita-ai-tools/releases/tag/v1.0.1

Package for Windows is up. No Linux yet, first need to get the docker image working again...

**Comment by feureau** [comment]
Awesome, thanks for the update! I'm using that version with krita 5.2.0 RC1
and it's working perfectly!

Thanks for the quick patch 😄
