### ISSUE TITLE
GroundingDINO support

### ISSUE THREAD

**Issue by extra-large-onions** [Acly/krita-ai-tools#10]
any future plan to add https://github.com/IDEA-Research/GroundingDINO (detect object with text) to this extension?
Thank you for your work on krita ai diffusion btw

**Comment by Acly** [comment]
Not from my side, having to input text sounds counter-intuitive. I was looking at the RAM+GroundingDINO+SAM combination at some point to automatically create masks for the whole image but ran into some issues.
