### ISSUE TITLE
[ Request ] Update for Krita 5.3.0-prealpha version ?

### ISSUE THREAD

**Issue by HuichanKIM** [Acly/krita-ai-tools#14]
Hi. Good tool!. 
I'd like to test new Krita 5.3.0-prealpha version. 
Unfortunately, your current tool does not even apply to the new version. 
If you have time, do you have any plans to update it for the 3.0 alpha version.

**Comment by Acly** [comment]
I plan to stick with official releases for now, keeping up with alphas creates a lot of overhead.

**Comment by HuichanKIM** [comment]
Sorry, too Late to find your message.  Thank you.
