### ISSUE TITLE
Doesn't seem to work with 5.2.2

### ISSUE THREAD

**Issue by yhslai** [Acly/krita-ai-tools#16]
I downloaded the built files from https://github.com/Acly/krita-ai-tools/releases/tag/v1.0.2 and drop them in my Krita installation path. However nothing seems to happen. No new button shown on the toolbar.

Krita version: 5.2.2

**Comment by Acly** [comment]
It should work, I'm using 5.2.2 too. Incompatibility will usually produce an error or crash, if it's just not there at all it's more likely files are missing or not in the right place.

**Comment by yhslai** [comment]
Anything that I should check specifically? It's just not shown:

![image](https://github.com/Acly/krita-ai-tools/assets/538696/d90470a5-d533-45b7-9913-90f360e929fa)

Is this the correct place to put the files? For example:

![image](https://github.com/Acly/krita-ai-tools/assets/538696/892f8bc1-de5b-4295-8413-c67f2ef6c9d2)

**Comment by Acly** [comment]
No it looks like you extracted into `Krita (x64)\bin`, it has to go into `Krita (x64)` directly. Should follow the existing file structure.

**Comment by yhslai** [comment]
Oh I see... that wat my negligence. Thank you for the answer.
