### ISSUE TITLE
Broken in 5.2.3

### ISSUE THREAD

**Issue by JukePlz** [Acly/krita-ai-tools#19]
Plugin no longer shows in tools after upgrading to 5.2.3

**Comment by Acly** [comment]
I've been using 5.2.3 for a few days, it seems to work without modifications.

How did you upgrade? Did you reinstall (extract/copy) the krita-ai-tools plugin afterwards?

**Comment by JukePlz** [comment]
Sorry, it seems that the update of Krita just overwrites the whole folder and thus deletes the plugin (doesn't happen with the Python plugins so I didn't suspect this), upon reinstall it seems to be working fine.

I'm closing this.
