### ISSUE TITLE
Recommended way to install in Arch Linux

### ISSUE THREAD

**Issue by zono50** [Acly/krita-ai-tools#24]
I see you can install it directly using Arch or yay, but then i run into the problem where if i go to tools > Scripts, then nothing pops out. I'm trying to use krita for it's ai diffusion. I can use an app image, but then when i try to install the plugin for the app image, i get the following error - 

APPDIR=/squashfs-root APPIMAGE=1 ./squashfs-root/AppRun                                                                                                                   ok  02:16:18 PM 
KCrash: crashing... crashRecursionCounter = 2
KCrash: Application Name = krita path = /home/zono50/Applications/krita/squashfs-root/usr/bin pid = 196258
KCrash: Arguments: /home/zono50/Applications/krita/squashfs-root/usr/bin/krita 
KCrash: Attempting to start /usr/lib/drkonqi
[1]  + 196258 suspended (signal)  APPDIR=/squashfs-root APPIMAGE=1 ./squashfs-root/AppRun

Would really like some guidance on this please.

**Comment by Acly** [comment]
There are no scripts. It adds two new tools in the toolbar.

**Comment by zono50** [comment]
Right, I understand that. What i'm saying is if i use the arch version, i can't get to scripts to even install krita ai diffusion in the first place. So what do I do then as far as that goes?

**Comment by Acly** [comment]
Ah this is about the diffusion plug-in? They're separate independent projects and work quite differently.

If you don't have any scripts at all (not even the ones that ship with Krita) maybe it's because your Krita doesn't have python support? Do you have the Python Plugin Manager in Krita's settings?
