### ISSUE TITLE
How to install it on a Krita Flatpak installation?

### ISSUE THREAD

**Issue by seth100** [Acly/krita-ai-tools#29]
Hi,

I have installed Krita 5.2.6 via Flathub,
I see that the resource folder is `~/.var/app/org.kde.krita/data/krita/`, how can I install the plugin?
I tried to create a folder `krita_segmentation_plugin` in there and put the content of the plugin taken from [the release page](https://github.com/Acly/krita-ai-tools/releases/download/v1.0.2/krita_segmentation_plugin-linux-x64-1.0.2.tar.gz) inside it, restarted Krita but I cannot find the new icons.
Can you please help?

Thanks

**Comment by aa956** [comment]
Check if you have krita flatpak installed as user or system:

```console
$ flatpak list --app -vv
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/username/.local/share/flatpak
darktable       org.darktable.Darktable 4.8.1   stable  user
FreeCAD org.freecadweb.FreeCAD  0.21.2.33771    stable  user
digiKam org.kde.digikam 8.4.0   stable  user
Krita   org.kde.krita   5.2.6   stable  user
$ 
```

If it's installed as user then correct path is `~/.local/share/flatpak` + `/app/org.kde.krita/current/active/files`:

```sh
tar xfz \
krita_segmentation_plugin-linux-x64-1.0.2.tar.gz \
--strip-components=1 \
-C ~/.local/share/flatpak/app/org.kde.krita/current/active/files
```

If installed as system (default I think, I'm installing flatpaks as user to reduce root partition size) then it shall be under `/var/lib/flatpak`, probably `/var/lib/flatpak/app/org.kde.krita/current/active/files`.

Do not forget to strip '/usr' from the archived files paths using tar's `--strip-components=1` parameter.

After krita restart:

![Screenshot_20241115_154733](https://github.com/user-attachments/assets/1aaba07d-02d7-4c76-b954-6075df6962d6)

**Comment by seth100** [comment]
@aa956 wow so clear, it works thanks 🙏🏼
