### ISSUE TITLE
Krita - 5.2.1 build?

### ISSUE THREAD

**Issue by matho53** [Acly/krita-ai-tools#5]
Is there any chance of a 5.2.1 build?

**Comment by Acly** [comment]
I've been using the 5.2.0 binaries also with 5.2.1, there was no reason to rebuild. Unless you encountered issues?

I can update the readme to mention 5.2.1

**Comment by Acly** [comment]
This is not a Python plugin, so it won't work like that. You have to extract the ZIP into your Krita installation folder (default is "C:\Program Files\Krita (x64)" if you didn't change it)

**Comment by matho53** [comment]
One should not assume 😊, hope its obvious I'm new to Krita. 
Thank you, segmentation installed and works like a charm!

**Comment by xiaojianan123** [comment]
According to your method, there are still no two icons. What's the reason? Mine is 5.2.3
