### ISSUE TITLE
No flatpack support?

### ISSUE THREAD

**Issue by SimonHeggie** [Acly/krita-ai-tools#6]
Hi,

First, thanks for your amazing working in elevating Krita's power. I have set this up with out any problem in windows and the tools worked excellently for me. Obviously because it's just dropping something in an install directory. Also loving your stable diffusion work; leaving Adobe in the dust for sure.

But for Linux I had a couple of questions;

"Get the Krita AppImage from the official source and extract it."

The app image from the website yeah? is it possible with flatpacks? 
Will there be flatpack support in the future?

Kind regards,

Simon.

**Comment by Acly** [comment]
The short answer is: as long as this remains an external plugin, it will always be a bit hacky.

Krita doesn't support external native plugins from a different location than its own installation path. When it's all bundled up in a AppImage or flatpack, it makes things difficult. Alternatively, if you installed via package manager, there are many distributions, with many package manager, which install it in different ways - not much better.

So there will be a flatpack or <your distribution of choice> package version only if someone decides to make one. 

Regarding shortcut: you can probably put the startup command in a .sh file and double-click it? I've never used a desktop shortcut on Linux in my life, why would you do that if you can enter mysterious cryptic commands instead ^^

You can also repack it into an AppImage, but when I tried that on a Fedora on my Laptop instead of the old Ubuntu that Krita is build on it threw some errors because some tool is newer version and became more pedantic and detected some issues, etc. etc. ... so unfortunately I cannot recommend that solution either.

> It's tough trying to convince people to give up windows when there's so many bars of entry for a beginner.

I've used Linux for years (both private and at work) and I've never been convinced to give up Windows either :D

Seriously though, I do understand installation is no very streamlined, but don't have a good idea that doesn't involve a lot of recurring effort.

**Comment by SimonHeggie** [comment]
Thanks for the explanation Acly.

Understanding that there doesn't seem much that can be done on the structure of the project.

As much as I chuckled at the mysterious cryptic commands thing; I think perhaps this where you can do the most good with the smallest effort; There a probably a lot of people like me who just need the smallest bit of help and then don't mind setting it up manually if all the instructions are provided. Even if you just explained it in what ever is your distro of choice; something like that for you may be trivial compared to the average artist trying to set i up themselves.

I genuinely believe that with the lower memory and software overhead of linux and the growing number of highly capable opensource software solutions including yours; that Linux as a VFX desktop platform is not only possible but preferable in a lot of cases. It's just a lot of little things like ensuring people can install and open up software with less clicks.


-S

**Comment by SimonHeggie** [comment]
Sorry for some reason github does wasn't to show the comments this as code... Let me know if you know how to get around it! 'Code' button doesn't help...

I have adjusted my script to store meta instead of the tar and appimage in order to optimise space. I guess I should try to find a github mirror of Krita so I can fix that problem.

`# Create the installation directory (in the user's home directory to avoid permission issues)
mkdir -p ~/Krita && cd ~/Krita

# Define URLs
KRITA_URL="https://binary-factory.kde.org/job/Krita_Stable_Appimage_Build/lastSuccessfulBuild/artifact/krita-5.2.1-e88f114a1c-x86_64.appimage"
SEGMENTATION_PLUGIN_URL=$(curl -s https://api.github.com/repos/Acly/krita-ai-tools/releases/latest | grep browser_download_url | grep tar.gz | cut -d '"' -f 4)

# Function to update metadata file
update_metadata() {
    local filename=$1
    local metadata_file=$2
    local size=$(stat -c%s "$filename")
    echo "$filename $size" > "$metadata_file"
}

# Function to check if file is up to date
is_up_to_date() {
    local filename=$1
    local metadata_file=$2
    if [ -f "$metadata_file" ]; then
        local saved_metadata=$(cat "$metadata_file")
        local current_metadata="$filename $(stat -c%s "$filename")"
        [ "$saved_metadata" = "$current_metadata" ]
    else
        return 1 # Not up to date if metadata file doesn't exist
    fi
}

# Download and extract Krita AppImage if not up to date
KRITA_METADATA="krita_metadata.txt"
if ! is_up_to_date "krita.appimage" "$KRITA_METADATA"; then
    wget -N -O krita.appimage "$KRITA_URL"
    chmod +x krita.appimage
    ./krita.appimage --appimage-extract
    update_metadata "krita.appimage" "$KRITA_METADATA"
fi

# Download and extract Segmentation Plugin if not up to date
SEGMENTATION_PLUGIN_METADATA="segmentation_plugin_metadata.txt"
if ! is_up_to_date "krita_segmentation_plugin.tar.gz" "$SEGMENTATION_PLUGIN_METADATA"; then
    wget -N -O krita_segmentation_plugin.tar.gz "$SEGMENTATION_PLUGIN_URL"
    tar -xf krita_segmentation_plugin.tar.gz -C squashfs-root/
    update_metadata "krita_segmentation_plugin.tar.gz" "$SEGMENTATION_PLUGIN_METADATA"
fi
`

**Comment by SimonHeggie** [comment]
Annnnd I can see why you were suggesting to build from scratch ahaha. 

only way we can use Github to ensure one command to fit all future updates for getting latest.

I'm thinking I may need to adjust the script to build from source after all...

**Comment by Acly** [comment]
Not sure what you mean by "build from source", that would be very linuxy, but have you ever built Krita before?
(btw code block is [three backticks ```](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code))

Anyway I think your best bet if you want to make it more accessible is to automate creating a AppImage/flatpack with the plugin included (maybe using GitHub Workflows).

**Comment by SimonHeggie** [comment]
Cheers. I got my script working; I'm no programmer either, I just asked GPT to do it. Lol.

```shell
#!/bin/bash

# Create the installation directory (in the user's home directory)
INSTALL_DIR=~/Krita
mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"

# Define the base URL for Krita downloads
BASE_KRITA_URL="https://binary-factory.kde.org/job/Krita_Stable_Appimage_Build/lastSuccessfulBuild/artifact/"

# Download the webpage and parse it to find the link to the latest Krita AppImage
KRITA_URL=$(curl -s $BASE_KRITA_URL | grep -o 'krita-.*\.appimage"' | head -1 | sed 's/"$//')

# Complete the URL for Krita AppImage
FULL_KRITA_URL="${BASE_KRITA_URL}${KRITA_URL}"

# Download the latest Krita AppImage if it doesn't already exist
if [ ! -f "$INSTALL_DIR/krita.appimage" ] || [ ! -s "$INSTALL_DIR/krita.appimage" ]; then
    wget -O "$INSTALL_DIR/krita.appimage" "$FULL_KRITA_URL"
fi

# Make the Krita AppImage executable
chmod +x "$INSTALL_DIR/krita.appimage"

# Extract Krita AppImage
"$INSTALL_DIR/krita.appimage" --appimage-extract

# Define URL for the latest segmentation plugin
SEGMENTATION_PLUGIN_URL=$(curl -s https://api.github.com/repos/Acly/krita-ai-tools/releases/latest | grep browser_download_url | grep tar.gz | cut -d '"' -f 4)

# Download the segmentation plugin if it doesn't already exist
if [ ! -f "$INSTALL_DIR/krita_segmentation_plugin.tar.gz" ] || [ ! -s "$INSTALL_DIR/krita_segmentation_plugin.tar.gz" ]; then
    wget -O "$INSTALL_DIR/krita_segmentation_plugin.tar.gz" "$SEGMENTATION_PLUGIN_URL"
fi

# Extract the segmentation plugin
tar -xf "$INSTALL_DIR/krita_segmentation_plugin.tar.gz" -C squashfs-root/

# Create a desktop shortcut for Krita
DESKTOP_FILE=~/.local/share/applications/krita.desktop
echo "[Desktop Entry]" > "$DESKTOP_FILE"
echo "Type=Application" >> "$DESKTOP_FILE"
echo "Name=Krita" >> "$DESKTOP_FILE"
echo "Icon=$INSTALL_DIR/squashfs-root/usr/share/icons/hicolor/512x512/apps/krita.png" >> "$DESKTOP_FILE"
echo "Exec=env APPDIR=$INSTALL_DIR/squashfs-root APPIMAGE=1 $INSTALL_DIR/squashfs-root/AppRun %U" >> "$DESKTOP_FILE"
echo "Terminal=false" >> "$DESKTOP_FILE"
echo "Categories=Graphics;" >> "$DESKTOP_FILE"
echo "StartupWMClass=krita" >> "$DESKTOP_FILE"

echo "Installation of Krita completed."

``` 

Only a couple more things to fix;

-Trying to get it to store a meta file with the last version number downloaded to determine whether a download is necessary

-Delete the AppImage and Tar file when done to optimize file size.

Not bad for a Linux noob! :D

-S

**Comment by SimonHeggie** [comment]
Done.

For you [Acly](https://github.com/Acly) I have taken the time to write an install script which will provided pretty much everything your average desktop user is going to need to for the next couple of releases until something breaks. But maybe this can be used to bring you more Linux users in the hopes you get more support.

Here's the install:

```shell
echo "Installing Krita to ~/.Applications/Krita (hidden in your home directory)"
INSTALL_DIR=~/.Applications/Krita
mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"

echo "Getting the latest download for Krita and Segmentation Tools"
BASE_KRITA_URL="https://binary-factory.kde.org/job/Krita_Stable_Appimage_Build/lastSuccessfulBuild/artifact/"
KRITA_PAGE=$(curl -s $BASE_KRITA_URL)
LATEST_KRITA_APPIMAGE=$(echo "$KRITA_PAGE" | grep -o 'krita-.*\.appimage"' | head -1 | sed 's/"$//')
LATEST_PLUGIN=$(curl -s https://api.github.com/repos/Acly/krita-ai-tools/releases/latest | grep browser_download_url | grep tar.gz | cut -d '"' -f 4)

echo "Checking to see if your version of Krita is up to date?"
if [ ! -f "$LATEST_KRITA_APPIMAGE" ]; then
    echo "Downloading new Krita"
    wget -O "$LATEST_KRITA_APPIMAGE" "${BASE_KRITA_URL}${LATEST_KRITA_APPIMAGE}"
    chmod +x "$LATEST_KRITA_APPIMAGE"
    "./$LATEST_KRITA_APPIMAGE" --appimage-extract
else
    echo "Latest Krita is already installed; moving on."
fi

echo "Updating the desktop file with correct paths"
EXTRACTED_DESKTOP_FILE="$INSTALL_DIR/squashfs-root/org.kde.krita.desktop"
ICON_PATH="$INSTALL_DIR/squashfs-root/krita.png"
if [ -f "$EXTRACTED_DESKTOP_FILE" ]; then
    echo "Pointing shortcut to Krita and tools"
    sed -i 's|^Exec=.*|Exec=env APPDIR='$INSTALL_DIR'/squashfs-root APPIMAGE=1 '$INSTALL_DIR'/squashfs-root/AppRun %U|' "$EXTRACTED_DESKTOP_FILE"
    sed -i 's|^Icon=.*|Icon='$ICON_PATH'|' "$EXTRACTED_DESKTOP_FILE"
    cp "$EXTRACTED_DESKTOP_FILE" ~/.local/share/applications/
else
    echo "Extracted desktop file not found, it could have been moved."
fi

echo "Checking if segmentation plugin is outdated"
if [ ! -f "$(basename "$LATEST_PLUGIN")" ]; then
    echo "Downloading new plugin"
    wget -O "$(basename "$LATEST_PLUGIN")" "$LATEST_PLUGIN"
    tar -xf "$(basename "$LATEST_PLUGIN")" -C squashfs-root/
else
    echo "Latest segmentation plugin is already installed."
fi

echo "DONE! Installed Krita with Segmentation tools built in."
echo "For more info go here: https://github.com/Acly/krita-ai-tools"

``` 

And the uninstall script:

```shell
# Ask for confirmation to uninstall Krita
read -p "Really, uninstall Krita? [Y/N] " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    # Define directories and files
    INSTALL_DIR=~/.Applications/Krita
    DESKTOP_FILE=~/.local/share/applications/org.kde.krita.desktop
    RESOURCE_DIR=~/.local/share/krita
    LOG_FILES=(~/.local/share/krita.log ~/.local/share/krita-sysinfo.log)

    # Ask whether to remove all related resources and log files
    echo "Uninstall all related resources and log files? [Y/N]"
    read -p "" -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        # Full Uninstall: Remove Krita, resource folders, and log files
        rm -rf "$INSTALL_DIR" "$DESKTOP_FILE" "$RESOURCE_DIR" "${LOG_FILES[@]}"
        echo "Full uninstall completed, including resources and log files."
    else
        # Standard Uninstall: Remove Krita and desktop file, preserve resources and logs
        rm -rf "$INSTALL_DIR" "$DESKTOP_FILE"
        echo "Uninstall completed, resources and log files preserved."
    fi
else
    echo "Uninstall aborted."
fi
``` 

I get now that you really just have to use terminal; because even something this complex you can simple copy and paste and walk off get a coffee and come back and everything is set up correctly with your segmentation tools.

Don't know about anyone else but this made my life easier!

-S
